[0m[[0m[0minfo[0m] [0m[0m[32mCircuitBreakerSpec:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32mCircuitBreaker[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- should pass successfully for all underlying successful calls[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32mCircuitBreaker[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- should remain closed for failures within threshold[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32mCircuitBreaker[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m- should move to open state for failures beyond threshold *** FAILED ***[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  java.lang.RuntimeException: error[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at TestBase.halfFailing(TestBase.scala:27)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at TestBase.$anonfun$halfFailing$1(TestBase.scala:38)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at scala.util.Try$.apply(Try.scala:213)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at circuitbreaker.CircuitBreaker$$anon$1.$anonfun$run$1(CircuitBreaker.scala:30)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at cats.effect.concurrent.Ref$SyncRef.spin$1(Ref.scala:251)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at cats.effect.concurrent.Ref$SyncRef.$anonfun$modify$1(Ref.scala:255)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:185)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at cats.effect.IO.unsafeRunTimed(IO.scala:320)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at cats.effect.IO.unsafeRunSync(IO.scala:239)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at CircuitBreakerSpec.$anonfun$new$16(CircuitBreakerSpec.scala:50)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  ...[0m[0m
